// Country → State → City cascading data
// Covers major countries with their states/provinces and key cities

const countryData = {
  "India": {
    "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Tirupati", "Rajahmundry", "Kakinada"],
    "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Tawang", "Ziro", "Pasighat"],
    "Assam": ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tezpur", "Tinsukia"],
    "Bihar": ["Patna", "Gaya", "Muzaffarpur", "Bhagalpur", "Darbhanga", "Purnia", "Arrah"],
    "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg", "Rajnandgaon"],
    "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
    "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar", "Bhavnagar", "Jamnagar", "Junagadh"],
    "Haryana": ["Gurugram", "Faridabad", "Panipat", "Ambala", "Karnal", "Hisar", "Rohtak"],
    "Himachal Pradesh": ["Shimla", "Manali", "Dharamshala", "Solan", "Mandi", "Kullu"],
    "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh", "Deoghar"],
    "Karnataka": ["Bengaluru", "Mysuru", "Mangaluru", "Hubli", "Belgaum", "Gulbarga", "Shimoga"],
    "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Kannur", "Alappuzha"],
    "Madhya Pradesh": ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Rewa"],
    "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Thane", "Kolhapur", "Solapur", "Navi Mumbai"],
    "Manipur": ["Imphal", "Thoubal", "Bishnupur", "Churachandpur"],
    "Meghalaya": ["Shillong", "Tura", "Jowai", "Nongstoin"],
    "Mizoram": ["Aizawl", "Lunglei", "Champhai", "Serchhip"],
    "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Tuensang"],
    "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Puri", "Berhampur", "Sambalpur"],
    "Punjab": ["Chandigarh", "Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali"],
    "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer", "Bikaner", "Alwar", "Jaisalmer"],
    "Sikkim": ["Gangtok", "Namchi", "Pelling", "Ravangla"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Erode", "Vellore"],
    "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam", "Secunderabad"],
    "Tripura": ["Agartala", "Udaipur", "Dharmanagar", "Kailashahar"],
    "Uttar Pradesh": ["Lucknow", "Noida", "Kanpur", "Agra", "Varanasi", "Allahabad", "Meerut", "Ghaziabad", "Greater Noida"],
    "Uttarakhand": ["Dehradun", "Haridwar", "Rishikesh", "Nainital", "Mussoorie", "Haldwani"],
    "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Siliguri", "Asansol", "Darjeeling", "Kharagpur"],
    "Delhi": ["New Delhi", "Delhi"],
  },
  "United States": {
    "California": ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento", "Oakland", "Fresno"],
    "New York": ["New York City", "Buffalo", "Rochester", "Albany", "Syracuse", "Yonkers"],
    "Texas": ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth", "El Paso", "Arlington"],
    "Florida": ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale", "St. Petersburg"],
    "Illinois": ["Chicago", "Aurora", "Naperville", "Rockford", "Springfield"],
    "Pennsylvania": ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading"],
    "Ohio": ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"],
    "Georgia": ["Atlanta", "Augusta", "Savannah", "Columbus", "Athens"],
    "Michigan": ["Detroit", "Grand Rapids", "Ann Arbor", "Lansing", "Flint"],
    "Washington": ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"],
    "Massachusetts": ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"],
    "Arizona": ["Phoenix", "Tucson", "Mesa", "Scottsdale", "Chandler"],
    "Colorado": ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Boulder"],
    "Nevada": ["Las Vegas", "Reno", "Henderson", "North Las Vegas"],
    "Oregon": ["Portland", "Salem", "Eugene", "Bend"],
  },
  "United Kingdom": {
    "England": ["London", "Manchester", "Birmingham", "Liverpool", "Leeds", "Bristol", "Oxford", "Cambridge", "Brighton", "Bath"],
    "Scotland": ["Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Inverness"],
    "Wales": ["Cardiff", "Swansea", "Newport", "Bangor"],
    "Northern Ireland": ["Belfast", "Derry", "Lisburn", "Newry"],
  },
  "Canada": {
    "Ontario": ["Toronto", "Ottawa", "Mississauga", "Hamilton", "London", "Brampton"],
    "British Columbia": ["Vancouver", "Victoria", "Surrey", "Burnaby", "Kelowna"],
    "Quebec": ["Montreal", "Quebec City", "Laval", "Gatineau"],
    "Alberta": ["Calgary", "Edmonton", "Red Deer", "Lethbridge"],
    "Manitoba": ["Winnipeg", "Brandon", "Steinbach"],
    "Saskatchewan": ["Saskatoon", "Regina", "Prince Albert"],
    "Nova Scotia": ["Halifax", "Sydney", "Dartmouth"],
  },
  "Australia": {
    "New South Wales": ["Sydney", "Newcastle", "Wollongong", "Central Coast"],
    "Victoria": ["Melbourne", "Geelong", "Ballarat", "Bendigo"],
    "Queensland": ["Brisbane", "Gold Coast", "Cairns", "Townsville", "Sunshine Coast"],
    "Western Australia": ["Perth", "Fremantle", "Bunbury"],
    "South Australia": ["Adelaide", "Mount Gambier"],
    "Tasmania": ["Hobart", "Launceston"],
  },
  "Germany": {
    "Bavaria": ["Munich", "Nuremberg", "Augsburg", "Regensburg"],
    "Berlin": ["Berlin"],
    "Hamburg": ["Hamburg"],
    "Hesse": ["Frankfurt", "Wiesbaden", "Kassel", "Darmstadt"],
    "North Rhine-Westphalia": ["Cologne", "Düsseldorf", "Dortmund", "Essen", "Bonn"],
    "Baden-Württemberg": ["Stuttgart", "Karlsruhe", "Mannheim", "Heidelberg", "Freiburg"],
    "Lower Saxony": ["Hanover", "Braunschweig", "Göttingen"],
    "Saxony": ["Dresden", "Leipzig", "Chemnitz"],
  },
  "France": {
    "Île-de-France": ["Paris", "Versailles", "Boulogne-Billancourt"],
    "Provence-Alpes-Côte d'Azur": ["Marseille", "Nice", "Cannes", "Toulon", "Aix-en-Provence"],
    "Auvergne-Rhône-Alpes": ["Lyon", "Grenoble", "Saint-Étienne", "Clermont-Ferrand"],
    "Nouvelle-Aquitaine": ["Bordeaux", "Limoges", "Poitiers"],
    "Occitanie": ["Toulouse", "Montpellier", "Nîmes", "Perpignan"],
    "Brittany": ["Rennes", "Brest", "Saint-Malo"],
    "Normandy": ["Rouen", "Le Havre", "Caen"],
  },
  "Japan": {
    "Tokyo": ["Tokyo", "Shibuya", "Shinjuku", "Minato"],
    "Osaka": ["Osaka", "Sakai", "Higashiosaka"],
    "Hokkaido": ["Sapporo", "Asahikawa", "Hakodate"],
    "Kyoto": ["Kyoto", "Uji"],
    "Kanagawa": ["Yokohama", "Kawasaki", "Sagamihara"],
    "Aichi": ["Nagoya", "Toyota", "Okazaki"],
    "Fukuoka": ["Fukuoka", "Kitakyushu"],
  },
  "China": {
    "Beijing": ["Beijing"],
    "Shanghai": ["Shanghai"],
    "Guangdong": ["Guangzhou", "Shenzhen", "Dongguan", "Foshan", "Zhuhai"],
    "Zhejiang": ["Hangzhou", "Ningbo", "Wenzhou"],
    "Jiangsu": ["Nanjing", "Suzhou", "Wuxi", "Changzhou"],
    "Sichuan": ["Chengdu", "Mianyang", "Leshan"],
    "Hubei": ["Wuhan", "Yichang", "Xiangyang"],
    "Shandong": ["Qingdao", "Jinan", "Yantai"],
  },
  "UAE": {
    "Dubai": ["Dubai", "Jebel Ali"],
    "Abu Dhabi": ["Abu Dhabi", "Al Ain"],
    "Sharjah": ["Sharjah"],
    "Ajman": ["Ajman"],
    "Ras Al Khaimah": ["Ras Al Khaimah"],
  },
  "Singapore": {
    "Central Region": ["Downtown Core", "Marina Bay", "Orchard", "Bugis"],
    "East Region": ["Tampines", "Bedok", "Changi"],
    "West Region": ["Jurong East", "Clementi", "Bukit Batok"],
    "North Region": ["Woodlands", "Yishun", "Sembawang"],
    "North-East Region": ["Sengkang", "Punggol", "Hougang"],
  },
  "Thailand": {
    "Bangkok": ["Bangkok", "Nonthaburi", "Pathum Thani"],
    "Chiang Mai": ["Chiang Mai", "Chiang Rai"],
    "Phuket": ["Phuket Town", "Patong", "Kata"],
    "Krabi": ["Krabi Town", "Ao Nang"],
    "Surat Thani": ["Ko Samui", "Ko Pha-ngan"],
  },
  "Malaysia": {
    "Kuala Lumpur": ["Kuala Lumpur"],
    "Selangor": ["Petaling Jaya", "Shah Alam", "Subang Jaya"],
    "Penang": ["George Town", "Bayan Lepas", "Butterworth"],
    "Johor": ["Johor Bahru", "Iskandar Puteri"],
    "Sabah": ["Kota Kinabalu", "Sandakan"],
    "Sarawak": ["Kuching", "Miri"],
  },
  "South Korea": {
    "Seoul": ["Seoul"],
    "Busan": ["Busan"],
    "Gyeonggi": ["Suwon", "Seongnam", "Goyang", "Incheon"],
    "Jeju": ["Jeju City", "Seogwipo"],
  },
  "Italy": {
    "Lazio": ["Rome", "Viterbo"],
    "Lombardy": ["Milan", "Bergamo", "Brescia", "Como"],
    "Veneto": ["Venice", "Verona", "Padua"],
    "Tuscany": ["Florence", "Pisa", "Siena", "Lucca"],
    "Campania": ["Naples", "Salerno", "Amalfi"],
    "Sicily": ["Palermo", "Catania", "Messina"],
  },
  "Spain": {
    "Community of Madrid": ["Madrid"],
    "Catalonia": ["Barcelona", "Girona", "Tarragona"],
    "Andalusia": ["Seville", "Málaga", "Granada", "Córdoba"],
    "Valencia": ["Valencia", "Alicante"],
    "Basque Country": ["Bilbao", "San Sebastián", "Vitoria"],
    "Balearic Islands": ["Palma de Mallorca", "Ibiza"],
  },
  "Brazil": {
    "São Paulo": ["São Paulo", "Campinas", "Santos"],
    "Rio de Janeiro": ["Rio de Janeiro", "Niterói"],
    "Minas Gerais": ["Belo Horizonte", "Uberlândia"],
    "Bahia": ["Salvador", "Feira de Santana"],
    "Paraná": ["Curitiba", "Londrina"],
    "Rio Grande do Sul": ["Porto Alegre", "Caxias do Sul"],
  },
  "Mexico": {
    "Mexico City": ["Mexico City"],
    "Jalisco": ["Guadalajara", "Puerto Vallarta", "Zapopan"],
    "Nuevo León": ["Monterrey", "San Pedro Garza García"],
    "Quintana Roo": ["Cancún", "Playa del Carmen", "Tulum"],
    "Yucatán": ["Mérida", "Valladolid"],
  },
  "South Africa": {
    "Gauteng": ["Johannesburg", "Pretoria", "Sandton"],
    "Western Cape": ["Cape Town", "Stellenbosch"],
    "KwaZulu-Natal": ["Durban", "Pietermaritzburg"],
    "Eastern Cape": ["Port Elizabeth", "East London"],
  },
  "Turkey": {
    "Istanbul": ["Istanbul"],
    "Ankara": ["Ankara"],
    "Antalya": ["Antalya", "Alanya", "Side"],
    "Izmir": ["Izmir", "Çeşme"],
    "Muğla": ["Bodrum", "Fethiye", "Marmaris"],
  },
  "Egypt": {
    "Cairo": ["Cairo", "Giza"],
    "Alexandria": ["Alexandria"],
    "Red Sea": ["Hurghada", "Sharm El-Sheikh"],
    "Luxor": ["Luxor"],
    "Aswan": ["Aswan"],
  },
  "Indonesia": {
    "Bali": ["Denpasar", "Ubud", "Seminyak", "Kuta", "Canggu"],
    "Jakarta": ["Jakarta"],
    "West Java": ["Bandung", "Bogor"],
    "Yogyakarta": ["Yogyakarta"],
    "East Java": ["Surabaya", "Malang"],
  },
  "Vietnam": {
    "Hanoi": ["Hanoi"],
    "Ho Chi Minh City": ["Ho Chi Minh City"],
    "Khanh Hoa": ["Nha Trang"],
    "Da Nang": ["Da Nang"],
    "Quang Nam": ["Hoi An"],
  },
  "Philippines": {
    "Metro Manila": ["Manila", "Makati", "Quezon City", "Taguig"],
    "Cebu": ["Cebu City", "Lapu-Lapu", "Mandaue"],
    "Palawan": ["Puerto Princesa", "El Nido", "Coron"],
  },
  "New Zealand": {
    "Auckland": ["Auckland"],
    "Wellington": ["Wellington"],
    "Canterbury": ["Christchurch"],
    "Otago": ["Queenstown", "Dunedin"],
  },
  "Portugal": {
    "Lisbon": ["Lisbon", "Cascais", "Sintra"],
    "Porto": ["Porto", "Vila Nova de Gaia"],
    "Algarve": ["Faro", "Lagos", "Albufeira"],
  },
  "Greece": {
    "Attica": ["Athens", "Piraeus"],
    "Central Macedonia": ["Thessaloniki"],
    "Crete": ["Heraklion", "Chania", "Rethymno"],
    "South Aegean": ["Santorini", "Mykonos", "Rhodes"],
  },
  "Netherlands": {
    "North Holland": ["Amsterdam", "Haarlem"],
    "South Holland": ["Rotterdam", "The Hague", "Leiden"],
    "Utrecht": ["Utrecht"],
    "North Brabant": ["Eindhoven", "Tilburg"],
  },
  "Switzerland": {
    "Zurich": ["Zurich"],
    "Bern": ["Bern", "Interlaken"],
    "Geneva": ["Geneva"],
    "Vaud": ["Lausanne", "Montreux"],
    "Lucerne": ["Lucerne"],
  },
  "Russia": {
    "Moscow": ["Moscow"],
    "Saint Petersburg": ["Saint Petersburg"],
    "Novosibirsk Oblast": ["Novosibirsk"],
    "Sverdlovsk Oblast": ["Yekaterinburg"],
    "Krasnodar Krai": ["Sochi", "Krasnodar"],
  },
  "Sri Lanka": {
    "Western Province": ["Colombo", "Negombo", "Mount Lavinia"],
    "Central Province": ["Kandy", "Nuwara Eliya"],
    "Southern Province": ["Galle", "Matara", "Unawatuna"],
  },
  "Nepal": {
    "Bagmati": ["Kathmandu", "Lalitpur", "Bhaktapur"],
    "Gandaki": ["Pokhara"],
    "Lumbini": ["Lumbini", "Butwal"],
  },
  "Bangladesh": {
    "Dhaka Division": ["Dhaka", "Narayanganj", "Gazipur"],
    "Chittagong Division": ["Chittagong", "Cox's Bazar"],
    "Sylhet Division": ["Sylhet"],
  },
  "Pakistan": {
    "Punjab": ["Lahore", "Faisalabad", "Rawalpindi", "Multan"],
    "Sindh": ["Karachi", "Hyderabad"],
    "Islamabad Capital Territory": ["Islamabad"],
    "Khyber Pakhtunkhwa": ["Peshawar", "Abbottabad"],
  },
  "Kenya": {
    "Nairobi": ["Nairobi"],
    "Coast": ["Mombasa", "Malindi", "Diani Beach"],
    "Rift Valley": ["Nakuru", "Naivasha"],
  },
  "Nigeria": {
    "Lagos": ["Lagos", "Ikeja", "Victoria Island"],
    "Abuja": ["Abuja"],
    "Rivers": ["Port Harcourt"],
  },
  "Argentina": {
    "Buenos Aires": ["Buenos Aires", "La Plata"],
    "Córdoba": ["Córdoba"],
    "Mendoza": ["Mendoza"],
    "Patagonia": ["Bariloche", "Ushuaia", "El Calafate"],
  },
  "Colombia": {
    "Bogotá D.C.": ["Bogotá"],
    "Antioquia": ["Medellín"],
    "Valle del Cauca": ["Cali"],
    "Bolívar": ["Cartagena"],
  },
  "Chile": {
    "Santiago Metropolitan": ["Santiago"],
    "Valparaíso": ["Valparaíso", "Viña del Mar"],
    "Los Lagos": ["Puerto Montt", "Puerto Varas"],
  },
  "Peru": {
    "Lima": ["Lima", "Miraflores"],
    "Cusco": ["Cusco"],
    "Arequipa": ["Arequipa"],
  },
  "Morocco": {
    "Casablanca-Settat": ["Casablanca"],
    "Rabat-Salé-Kénitra": ["Rabat"],
    "Marrakech-Safi": ["Marrakech", "Essaouira"],
    "Fès-Meknès": ["Fes", "Meknes"],
    "Tanger-Tetouan-Al Hoceima": ["Tangier", "Chefchaouen"],
  },
  "Saudi Arabia": {
    "Riyadh": ["Riyadh"],
    "Makkah": ["Jeddah", "Mecca"],
    "Eastern Province": ["Dammam", "Dhahran", "Al Khobar"],
    "Madinah": ["Medina"],
  },
  "Qatar": {
    "Doha": ["Doha", "The Pearl", "Lusail"],
    "Al Wakrah": ["Al Wakrah"],
  },
  "Oman": {
    "Muscat": ["Muscat", "Muttrah"],
    "Dhofar": ["Salalah"],
  },
  "Bahrain": {
    "Capital": ["Manama"],
    "Muharraq": ["Muharraq"],
  },
  "Kuwait": {
    "Al Asimah": ["Kuwait City"],
    "Hawalli": ["Hawalli", "Salmiya"],
  },
  "Jordan": {
    "Amman": ["Amman"],
    "Aqaba": ["Aqaba"],
    "Ma'an": ["Petra", "Wadi Rum"],
  },
  "Israel": {
    "Tel Aviv District": ["Tel Aviv", "Herzliya"],
    "Jerusalem District": ["Jerusalem"],
    "Haifa District": ["Haifa"],
  },
  "Sweden": {
    "Stockholm": ["Stockholm"],
    "Västra Götaland": ["Gothenburg"],
    "Skåne": ["Malmö", "Lund"],
  },
  "Norway": {
    "Oslo": ["Oslo"],
    "Vestland": ["Bergen"],
    "Troms og Finnmark": ["Tromsø"],
  },
  "Denmark": {
    "Capital Region": ["Copenhagen"],
    "Central Denmark": ["Aarhus"],
    "Southern Denmark": ["Odense"],
  },
  "Finland": {
    "Uusimaa": ["Helsinki", "Espoo", "Vantaa"],
    "Pirkanmaa": ["Tampere"],
    "Southwest Finland": ["Turku"],
    "Lapland": ["Rovaniemi"],
  },
  "Ireland": {
    "Leinster": ["Dublin", "Kilkenny"],
    "Munster": ["Cork", "Limerick", "Galway"],
    "Connacht": ["Galway"],
  },
  "Austria": {
    "Vienna": ["Vienna"],
    "Salzburg": ["Salzburg"],
    "Tyrol": ["Innsbruck"],
    "Styria": ["Graz"],
  },
  "Belgium": {
    "Brussels-Capital": ["Brussels"],
    "Flanders": ["Antwerp", "Ghent", "Bruges"],
    "Wallonia": ["Liège", "Namur"],
  },
  "Poland": {
    "Masovia": ["Warsaw"],
    "Lesser Poland": ["Kraków"],
    "Pomerania": ["Gdańsk"],
    "Greater Poland": ["Poznań"],
    "Lower Silesia": ["Wrocław"],
  },
  "Czech Republic": {
    "Prague": ["Prague"],
    "South Moravian": ["Brno"],
    "Moravian-Silesian": ["Ostrava"],
  },
  "Hungary": {
    "Budapest": ["Budapest"],
    "Hajdú-Bihar": ["Debrecen"],
    "Baranya": ["Pécs"],
  },
  "Romania": {
    "Bucharest": ["Bucharest"],
    "Cluj": ["Cluj-Napoca"],
    "Constanța": ["Constanța"],
    "Brașov": ["Brașov"],
  },
  "Croatia": {
    "City of Zagreb": ["Zagreb"],
    "Split-Dalmatia": ["Split"],
    "Dubrovnik-Neretva": ["Dubrovnik"],
    "Istria": ["Pula", "Rovinj"],
  },
  "Maldives": {
    "Malé Atoll": ["Malé"],
    "South Ari Atoll": ["Mahibadhoo"],
    "Baa Atoll": ["Eydhafushi"],
  },
  "Mauritius": {
    "Port Louis": ["Port Louis"],
    "Rivière du Rempart": ["Grand Baie"],
    "Black River": ["Flic en Flac"],
  },
};

// Country code mapping for phone validation
export const countryCodes = {
  "India": "+91",
  "United States": "+1",
  "United Kingdom": "+44",
  "Canada": "+1",
  "Australia": "+61",
  "Germany": "+49",
  "France": "+33",
  "Japan": "+81",
  "China": "+86",
  "UAE": "+971",
  "Singapore": "+65",
  "Thailand": "+66",
  "Malaysia": "+60",
  "South Korea": "+82",
  "Italy": "+39",
  "Spain": "+34",
  "Brazil": "+55",
  "Mexico": "+52",
  "South Africa": "+27",
  "Turkey": "+90",
  "Egypt": "+20",
  "Indonesia": "+62",
  "Vietnam": "+84",
  "Philippines": "+63",
  "New Zealand": "+64",
  "Portugal": "+351",
  "Greece": "+30",
  "Netherlands": "+31",
  "Switzerland": "+41",
  "Russia": "+7",
  "Sri Lanka": "+94",
  "Nepal": "+977",
  "Bangladesh": "+880",
  "Pakistan": "+92",
  "Kenya": "+254",
  "Nigeria": "+234",
  "Argentina": "+54",
  "Colombia": "+57",
  "Chile": "+56",
  "Peru": "+51",
  "Morocco": "+212",
  "Saudi Arabia": "+966",
  "Qatar": "+974",
  "Oman": "+968",
  "Bahrain": "+973",
  "Kuwait": "+965",
  "Jordan": "+962",
  "Israel": "+972",
  "Sweden": "+46",
  "Norway": "+47",
  "Denmark": "+45",
  "Finland": "+358",
  "Ireland": "+353",
  "Austria": "+43",
  "Belgium": "+32",
  "Poland": "+48",
  "Czech Republic": "+420",
  "Hungary": "+36",
  "Romania": "+40",
  "Croatia": "+385",
  "Maldives": "+960",
  "Mauritius": "+230",
};

export default countryData;
